### ISSUE TITLE
Minor error at step C of Makefile

### ISSUE THREAD

**Issue by tiagolbiotech** [NP-Omix/BioCompass#36]
Step C of Makefile presents the following error

```
# C. Extending table_1 with best hits
python table_1_extender.py PAL 028
rm temp.txt
rm: temp.txt: No such file or directory
```

**Comment by castelao** [comment]
The Makefile in both branches (master & dev) are different than that, they use `-rm`, like:

```
# C. Extending table_1 with best hits
python table_1_extender.py $(REFNAME) $*
-rm temp.txt
```

Did you edited it locally? Maybe removed the '-' by mistake?

**Comment by castelao** [comment]
I'll assume it's working now, so I'll close this. If you still have a problem here, please reopen and give more details.

Anyways, table_1_extender.py is being replaced.
